### ISSUE TITLE
Fix the image of the middle content of the home page.

### ISSUE THREAD

**Issue by vijayyprajapati** [DSC-JSS-NOIDA/Learn-Quest#20]

**Comment by xoxo16** [comment]
please assign this issue to me

**Comment by vijayyprajapati** [comment]
Sure @xoxo16 !!!
 Go ahead.

**Comment by yujit2003** [comment]
Please assign this to me

**Comment by Abhash-Chakraborty** [comment]
Please assign this to me

**Comment by albetros24** [comment]
it would be a great opportunity  if I could work on it

**Comment by Olorunsolavictor** [comment]
I can help with this if you assign it to me.

**Comment by vijayyprajapati** [comment]
this issue has been resovled
