### ISSUE TITLE
In categories section links for data structure and algoritham are not working. fix them

### ISSUE THREAD

**Issue by vijayyprajapati** [DSC-JSS-NOIDA/Learn-Quest#23]

**Comment by Sonukumarkeshri4** [comment]
Need to make changes in naming as domain and subdomain are not fetched in final deployed version.
I can go for this. Please assign it to me;

**Comment by Ski1ledHawkeye** [comment]
Can you assign me this issue??

**Comment by vijayyprajapati** [comment]
Go for it @Sonukumarkeshri4

**Comment by Sonukumarkeshri4** [comment]
I have resolved it,  Please check [PULL Request 42](https://github.com/DSC-JSS-NOIDA/Learn-Quest/pull/42)
