### ISSUE TITLE
Changing of h1 from quick-learn to learn-quest

### ISSUE THREAD

**Issue by 2CoolBob** [DSC-JSS-NOIDA/Learn-Quest#31]

**Comment by 2CoolBob** [comment]
Pls assign this to me. As i can make it more i catchy

**Comment by Ski1ledHawkeye** [comment]
Assign this to me @vijayyprajapati @RitikaGarg-tech

**Comment by albetros24** [comment]
can u please assign this  issue to me   I would love to  resolve it
