### ISSUE TITLE
LearnQuest title is clickable but doesn't leads to home page on clicking

### ISSUE THREAD

**Issue by ampsteric** [DSC-JSS-NOIDA/Learn-Quest#32]
This is happening on all pages and thus leads to a bad user experience.
Please assign me this issue as a part of hacktoberfest so that I can start working on it.
![image](https://user-images.githubusercontent.com/56419358/193441859-77e54fdb-efc7-44da-8f11-918d4f6678b8.png)

**Comment by sdhanraj300** [comment]
Assign this to me.

**Comment by ampsteric** [comment]
@sdhanraj300 i have already implemented it in local , waiting to get assigned to submit PR.

**Comment by ampsteric** [comment]
@rucha0702 can you please assign this to me so that I can submit the PR for review

**Comment by vijayyprajapati** [comment]
Go ahead @ampsteric
