### ISSUE TITLE
icons(links) arent working also might provide a bad impression 

### ISSUE THREAD

**Issue by 2CoolBob** [DSC-JSS-NOIDA/Learn-Quest#34]
<img width="956" alt="2022-10-02" src="https://user-images.githubusercontent.com/114845404/193442335-3f51442f-80dc-4829-9861-68734b2730fc.png">

**Comment by GyanPrakashRaj** [comment]
i have created and designed their contact links... waiting to be merge

**Comment by vijayyprajapati** [comment]
This issue has been resolved.
