### ISSUE TITLE
improve fonts on home page for paragraph 

### ISSUE THREAD

**Issue by 2CoolBob** [DSC-JSS-NOIDA/Learn-Quest#37]

**Comment by 2CoolBob** [comment]
hey @vijayyprajapati  i have change the font color and text-sizing of heading. Do consider it
before
<img width="960" alt="2022-10-02 (6)" src="https://user-images.githubusercontent.com/114845404/193450436-77924139-56cd-4ea6-ae51-8d2e1640c23c.png">
after
<img width="960" alt="2022-10-02 (8)" src="https://user-images.githubusercontent.com/114845404/193450485-9562335b-6d04-46b3-b496-fb338df11bd3.png">
<img width="960" alt="2022-10-02 (9)" src="https://user-images.githubusercontent.com/114845404/193450503-9b307943-79d9-4a01-8ac5-a15763199f8e.png">

**Comment by 2CoolBob** [comment]
hey @vijayyprajapati i have made some changes in the font section of the home page.
Before 
<img width="954" alt="2022-10-02 (2)" src="https://user-images.githubusercontent.com/114845404/193450725-cf4773c9-6327-4e93-8440-c396625b1a5d.png">
After

<img width="960" alt="2022-10-02 (7)" src="https://user-images.githubusercontent.com/114845404/193450759-2021da98-a7da-4a56-b554-8c08c5ed3843.png">
<img width="960" alt="2022-10-02 (9)" src="https://user-images.githubusercontent.com/114845404/193451045-14a27754-0894-43e3-8b15-968b682aaf0e.png">

**Comment by vijayyprajapati** [comment]
Changes are looking quite good. Go for it @2CoolBob

**Comment by PranjalSays** [comment]
Hey @vijayyprajapati  i have made the changes as per your requirement
before
<img width="960" alt="2022-10-02 (6)" src="https://user-images.githubusercontent.com/97930487/193453485-da44e5f3-922e-43ed-991a-d64d45680645.png">
after
<img width="959" alt="2022-10-02 (8)" src="https://user-images.githubusercontent.com/97930487/193453489-5a393a08-6581-44cd-b0a8-973f4dbd81fe.png">
<img width="960" alt="2022-10-02 (9)" src="https://user-images.githubusercontent.com/97930487/193453493-0f67c323-a0e0-47ef-9606-57e69d702f15.png">
