### ISSUE TITLE
Changes in content of Contribution Guidelines 

### ISSUE THREAD

**Issue by PranjalSays** [DSC-JSS-NOIDA/Learn-Quest#43]
Hey @vijayyprajapati @RitikaGarg-tech i have made changes in the content part of contribution guidelines as it wasnt updated according to new github norms  and also i have triggered the link on this page "DSC-JSS-Noida".
Before 
<img width="960" alt="2022-10-03" src="https://user-images.githubusercontent.com/97930487/193533792-c1da264b-c4ee-4e34-9d19-556dd311b180.png">
After
<img width="960" alt="2022-10-03 (4)" src="https://user-images.githubusercontent.com/97930487/193533835-90eaff02-e124-498c-99cc-a0fe146c9294.png">
<img width="960" alt="2022-10-03 (2)" src="https://user-images.githubusercontent.com/97930487/193533853-eee72e11-6005-4797-b1bb-3bb6a35102eb.png">
Hope you like them.

**Comment by RitikaGarg-tech** [comment]
@PranjalSays we'll merge them.
