### ISSUE TITLE
Adding Scroll Back To Top feature for Resource Page

### ISSUE THREAD

**Issue by yasaswini999** [DSC-JSS-NOIDA/Learn-Quest#48]
Hey @vijayyprajapati !
New Opensource dev here ! could you please assign me the task of creating a "scroll to top" button that becomes visible when the user starts to scroll the page at the end of the Resources page.
![image](https://user-images.githubusercontent.com/106906121/193755227-a285f26a-b40b-4df0-a121-b603c9218713.png)

**Comment by AdarshBajpai67** [comment]
I would like to work on this issue, Please assign me

**Comment by AdarshBajpai67** [comment]
I have solved the issue in #50 
I have raised the PR , please review the PR

**Comment by vijayyprajapati** [comment]
Hey @yasaswini999 
The issue has been resolved.
Thank you for showing interest.
Try to fine another issue and raise a PR.
