### ISSUE TITLE
Remove Cards from features section. Take reference from the design provided.

### ISSUE THREAD

**Issue by vijayyprajapati** [DSC-JSS-NOIDA/Learn-Quest#55]

**Comment by 2802AdityA** [comment]
Hey @vijayyprajapati can you please provide the reference?

**Comment by vijayyprajapati** [comment]
Hey @2802AdityA  
In the repository, there is a folder named design when you open that folder you can find a file named figma_link.docx. in that file you can get the design link.

**Comment by 2802AdityA** [comment]
Thank You @vijayyprajapati 
I can do this task. Please assign this to me.

**Comment by vijayyprajapati** [comment]
okaay @2802AdityA
